# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62d884cd1fc20723e2c3d8c9cbef55d9721969b2e8ebfa4b34b2f8d484ebfd1a15a2d5592349bea348fa67568b02b795dbdc5617e3be820a2ca0e58c23042f35

test:
  secret_key_base: b09e40a62bde4c865ee9f65ef40be3fb24e42ae26c902aab0565443509087047647a80bd7ae2cb6cb49ea8f26bc7d87b2ef61a20cba391523d7fd34c1371c2ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
